### ISSUE TITLE
[2.18] MPD_HOST no longer seems to work with a password, --host works

### ISSUE THREAD

**Issue by lnikkila** [MusicPlayerDaemon/libmpdclient#52] opened 2020-03-19 11:00 UTC
It looks like passwords in an environment variable no longer work after updating to libmpdclient 2.18 and mpc 0.33:

```sh-session
$ MPD_HOST='pass@10.0.0.100' mpc status
MPD error: Failed to resolve host name
```

However passing `--host` works as expected:
```sh-session
$ mpc status --host 'pass@10.0.0.100'
volume: n/a   repeat: off   random: off   single: off   consume: on
```

I believe this may be due to  <https://github.com/MusicPlayerDaemon/libmpdclient/commit/e7c4c125d093f322f5219ee213a2693d605af4df>.

**Comment by cataldor** [comment] 2020-03-24 11:33
Hello @Inikkila
Thank you for reporting this and sorry for the delay

Unfortunately, i was unable to reproduce your problem; both forms worked here.
Are you running on Windows? which version?

because the problem is happening in the resolver which has different code for unix/windows
https://github.com/MusicPlayerDaemon/libmpdclient/blob/e30bf21c8e166bccdaed6c6e3d437880ad742362/src/socket.c#L135-L138

**Comment by lnikkila** [comment] 2020-03-24 15:58
That's interesting! I'm using Linux, GNU Guix to be specific:

```sh-session
$ uname -a
Linux laptop 5.4.26-gnu #1 SMP 1 x86_64 GNU/Linux

$ guix describe
Generation 41	Mar 19 2020 15:09:59	(current)
  guix ac75bd0
    repository URL: https://git.savannah.gnu.org/git/guix.git
    branch: master
    commit: ac75bd010260f6a722e1723b35992b04fd79d44c

$ guix package --show=mpd-mpc
name: mpd-mpc
version: 0.33
dependencies: libmpdclient@2.18 pkg-config@0.29.2 python-sphinx@2.3.1
location: gnu/packages/mpd.scm:160:2

$ guix package --show=libmpdclient
name: libmpdclient
version: 2.18
dependencies: check@0.14.0 doxygen@1.8.15 pkg-config@0.29.2
location: gnu/packages/mpd.scm:61:2
```

[These package definitions can be found here.](
https://github.com/guix-mirror/guix/blob/ac75bd010260f6a722e1723b35992b04fd79d44c/gnu/packages/mpd.scm#L60-L181)

For the time being, I created my own mpc@0.33 package that pulls in libmpdclient@2.17 instead built from source, this seems to work as it did before.

Should I try building the official package with debug symbols enabled and attach a gdb breakpoint to pull a stack trace?

**Comment by cataldor** [comment] 2020-03-26 12:47
Thanks for the detailed response!
that's weird.. so it must be that commit.
I will take another look

if you can build with debug symbols and check the host variable it would be of great help. Probably the host for `MPD_HOST` is messed up

**Comment by cataldor** [comment] 2020-03-27 14:28
Okay, i found it; its an off-by-one write
i will be submitting a patch shortly; i'm finishing another one

**Comment by cataldor** [comment] 2020-04-03 11:09
Hello @lnikkila 
the patch has been merged into libmpdclient.
Could you run the test with this version so we can close this issue?

best regards

**Comment by MaxKellermann** [comment] 2020-07-03 15:22
b84a93245eab2747520f252ac7d6c79630c7f2de

**Closed by MaxKellermann** 2020-07-03 15:22 UTC

**Comment by lnikkila** [comment] 2020-07-04 17:09
Ah sorry for the late reply, this fixed the issue. Thank you!
